application: research-methods-dojo
version: 0
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /static
  static_dir: static
  secure: always

- url: /.*
  script: index.py
  secure: always

builtins:
- remote_api: on